### ISSUE TITLE
Error while running MongoDB atomic app

### ISSUE THREAD

**Issue by tuxdna** [projectatomic/nulecule-library#64]
I am running the MongoDB atomic app as shown below on Fedora 23:

```
$ sudo atomic run kolab/mongodb-centos7-atomicapp --provider docker
```

Here is the output:

```
$ sudo atomic run kolab/mongodb-centos7-atomicapp --provider docker
docker run -it --rm  --privileged -v /tmp/aa:/atomicapp -v /run:/run -v /:/host --net=host --name mongodb-centos7-atomicapp -e NAME=mongodb-centos7-atomicapp -e IMAGE=kolab/mongodb-centos7-atomicapp kolab/mongodb-centos7-atomicapp -v  run  kolab/mongodb-centos7-atomicapp --provider docker
docker run -it --rm  --privileged -v /tmp/aa:/atomicapp -v /run:/run -v /:/host --net=host --name mongodb-centos7-atomicapp -e NAME=mongodb-centos7-atomicapp -e IMAGE=kolab/mongodb-centos7-atomicapp kolab/mongodb-centos7-atomicapp -v  run  kolab/mongodb-centos7-atomicapp --provider docker
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
2016-03-07 10:49:08,165 - atomicapp.plugin - DEBUG - Loading providers from /usr/lib/python2.7/site-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/providers
2016-03-07 10:49:08,172 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: /host/var/lib/atomicapp/kolab-mongodb-centos7-atomicapp-ea43378d3582
2016-03-07 10:49:08,172 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: kolab/mongodb-centos7-atomicapp
2016-03-07 10:49:08,173 - atomicapp.nulecule.main - DEBUG - Request to unpack to kolab/mongodb-centos7-atomicapp to /host/var/lib/atomicapp/kolab-mongodb-centos7-atomicapp-ea43378d3582
2016-03-07 10:49:08,173 - atomicapp.nulecule.base - INFO - Unpacking image: kolab/mongodb-centos7-atomicapp to /host/var/lib/atomicapp/kolab-mongodb-centos7-atomicapp-ea43378d3582
2016-03-07 10:49:08,347 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: kolab/mongodb-centos7-atomicapp
2016-03-07 10:49:08,347 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: kolab/mongodb-centos7-atomicapp to /host/var/lib/atomicapp/kolab-mongodb-centos7-atomicapp-ea43378d3582
2016-03-07 10:49:08,347 - atomicapp.nulecule.container - DEBUG - Running Docker container: /usr/bin/docker run -d --entrypoint /bin/true kolab/mongodb-centos7-atomicapp
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
2016-03-07 10:49:08,984 - atomicapp.nulecule.container - DEBUG - Copying data from Docker container: /usr/bin/docker cp 2068c7cc49de8322a0f2067de8880c1d05c58043f7b5123138ea10945f52190a:/application-entity /tmp/nulecule-386de952-e452-11e5-98e8-507b9d815541
2016-03-07 10:49:09,051 - atomicapp.nulecule.container - DEBUG - Copying nulecule data from /tmp/nulecule-386de952-e452-11e5-98e8-507b9d815541 to /host/var/lib/atomicapp/kolab-mongodb-centos7-atomicapp-ea43378d3582
2016-03-07 10:49:09,053 - atomicapp.nulecule.container - DEBUG - Removing tmp dir: /tmp/nulecule-386de952-e452-11e5-98e8-507b9d815541
2016-03-07 10:49:09,055 - atomicapp.nulecule.container - DEBUG - Removing Docker container: /usr/bin/docker rm -f 2068c7cc49de8322a0f2067de8880c1d05c58043f7b5123138ea10945f52190a
2068c7cc49de8322a0f2067de8880c1d05c58043f7b5123138ea10945f52190a
mongodb_admin_password (MongoDB Administrator password): u
mongodb_database (MongoDB Database name): u
mongodb_password (Password for the $mongodb_user account): u
mongodb_username (User name for MongoDB account to be created): u
2016-03-07 10:49:14,241 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2016-03-07 10:49:14,241 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2016-03-07 10:49:14,241 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2016-03-07 10:49:14,241 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2016-03-07 10:49:14,241 - docker - DEBUG - Given config: {u'mongodb_admin_password': 'u', u'image': u'centos/mongodb-26-centos7', 'namespace': 'default', u'mongodb_username': 'u', u'mongodb_password': 'u', 'provider': 'kubernetes', u'mongodb_noprealloc': True, u'mongodb_smallfiles': True, u'mongodb_quiet': True, u'mongodb_database': 'u'}
2016-03-07 10:49:14,241 - docker - DEBUG - Namespace: default
2016-03-07 10:49:14,293 - docker - INFO - Deploying to provider: Docker
2016-03-07 10:49:14,330 - docker - INFO - WARNING: Using --name provided within artifact file.
Unable to find image '\:latest' locally
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
2016-03-07 10:49:14,348 - atomicapp.cli.main - ERROR - Command '['docker', 'run', '-d', '\\', '--name', 'mongodb-atomicapp-app', '\\', '-e', 'MONGODB_ADMIN_PASSWORD=u', '\\', '-e', 'MONGODB_DATABASE=u', '\\', '-e', 'MONGODB_NOPREALLOC=True', '\\', '-e', 'MONGODB_PASSWORD=u', '\\', '-e', 'MONGODB_QUIET=True', '\\', '-e', 'MONGODB_SMALLFILES=True', '\\', '-e', 'MONGODB_USERNAME=u', '\\', '-p', '27017:27017', '\\', 'centos/mongodb-26-centos7']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/cli/main.py", line 71, in cli_run
    nm.run(**argdict)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/nulecule/main.py", line 170, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/nulecule/base.py", line 132, in run
    component.run(provider_key, dryrun)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/nulecule/base.py", line 261, in run
    provider.deploy()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/providers/docker.py", line 97, in deploy
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'run', '-d', '\\', '--name', 'mongodb-atomicapp-app', '\\', '-e', 'MONGODB_ADMIN_PASSWORD=u', '\\', '-e', 'MONGODB_DATABASE=u', '\\', '-e', 'MONGODB_NOPREALLOC=True', '\\', '-e', 'MONGODB_PASSWORD=u', '\\', '-e', 'MONGODB_QUIET=True', '\\', '-e', 'MONGODB_SMALLFILES=True', '\\', '-e', 'MONGODB_USERNAME=u', '\\', '-p', '27017:27017', '\\', 'centos/mongodb-26-centos7']' returned non-zero exit status 1
```

On inspecting output of docker command in Python shell:

```
$ ipython
In [1]: l = ['docker', 'run', '-d', '\\', '--name', 'mongodb-atomicapp-app', '\\', '-e', 'MONGODB_ADMIN_PASSWORD=u', '\\', '-e', 'MONGODB_DATABASE=u', '\\', '-e', 'MONGODB_NOPREALLOC=True', '\\', '-e', 'MONGODB_PASSWORD=u', '\\', '-e', 'MONGODB_QUIET=True', '\\', '-e', 'MONGODB_SMALLFILES=True', '\\', '-e', 'MONGODB_USERNAME=u', '\\', '-p', '27017:27017', '\\', 'centos/mongodb-26-centos7']
In [3]: print " ".join(l)
docker run -d \ --name mongodb-atomicapp-app \ -e MONGODB_ADMIN_PASSWORD=u \ -e MONGODB_DATABASE=u \ -e MONGODB_NOPREALLOC=True \ -e MONGODB_PASSWORD=u \ -e MONGODB_QUIET=True \ -e MONGODB_SMALLFILES=True \ -e MONGODB_USERNAME=u \ -p 27017:27017 \ centos/mongodb-26-centos7
```

And then I ran the command again:

```
$ sudo docker run -d \ --name mongodb-atomicapp-app \ -e MONGODB_ADMIN_PASSWORD=u \ -e MONGODB_DATABASE=u \ -e MONGODB_NOPREALLOC=True \ -e MONGODB_PASSWORD=u \ -e MONGODB_QUIET=True \ -e MONGODB_SMALLFILES=True \ -e MONGODB_USERNAME=u \ -p 27017:27017 \ centos/mongodb-26-centos7
Unable to find image ' --name:latest' locally
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"

```

This seems like a bug in MongoDB AtomicApp itself.

**Comment by tuxdna** [comment]
After removing backslashes from the docker command it seems to work:

```
sudo docker run -d --name mongodb-atomicapp-app -e MONGODB_ADMIN_PASSWORD=u -e MONGODB_DATABASE=u -e MONGODB_NOPREALLOC=True -e MONGODB_PASSWORD=u -e MONGODB_QUIET=True -e MONGODB_SMALLFILES=True -e MONGODB_USERNAME=u -p 27017:27017 centos/mongodb-26-centos7

Unable to find image 'centos/mongodb-26-centos7:latest' locally
Trying to pull repository docker.io/centos/mongodb-26-centos7 ... latest: Pulling from centos/mongodb-26-centos7
612904ee5e62: Downloading [===================>                               ] 50.73 MB/130.8 MB


```

**Comment by tuxdna** [comment]
Running the container without -d flag gives following output:

```
$ sudo docker run -e MONGODB_ADMIN_PASSWORD=u -e MONGODB_DATABASE=u -e MONGODB_NOPREALLOC=True -e MONGODB_PASSWORD=u -e MONGODB_QUIET=True -e MONGODB_SMALLFILES=True -e MONGODB_USERNAME=u -p 27017:27017 centos/mongodb-26-centos7
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
=> Waiting for container IP address ... 172.17.0.4:27017
You must specify the following environment variables:
  MONGODB_USER
  MONGODB_PASSWORD
  MONGODB_DATABASE
  MONGODB_ADMIN_PASSWORD
Optional variables:
  MONGODB_REPLICA_NAME
MongoDB settings:
  MONGODB_NOPREALLOC (default: true)
  MONGODB_SMALLFILES (default: true)
  MONGODB_QUIET (default: true)
```

Now, the container expects `MONGODB_USER` while `MONGODB_USERNAME` is being provided. Therefore it fails to start.

**Comment by tuxdna** [comment]
And vala, it works with correct env variable `MONGODB_USER`:

```
$ sudo docker run -e MONGODB_ADMIN_PASSWORD=u -e MONGODB_DATABASE=u -e MONGODB_NOPREALLOC=True -e MONGODB_PASSWORD=u -e MONGODB_QUIET=True -e MONGODB_SMALLFILES=True -e MONGODB_USER=u -p 27017:27017 centos/mongodb-26-centos7
=> Waiting for container IP address ...Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 172.17.0.4:27017
=> Waiting for MongoDB service startup  ...
note: noprealloc may hurt performance in many applications
2016-03-07T11:25:15.661+0000 [initandlisten] MongoDB starting : pid=31 port=27017 dbpath=/var/lib/mongodb/data 64-bit host=95fffc85f581
2016-03-07T11:25:15.661+0000 [initandlisten] db version v2.6.9

... OUTPUT SKIPPED ...

2016-03-07T11:25:21.064+0000 [initandlisten] recover : no journal files present, no recovery needed
2016-03-07T11:25:21.089+0000 [initandlisten] waiting for connections on port 27017

```

**Comment by tuxdna** [comment]
The parent image has changed the env variable from `MONGODB_USERNAME` to `MONGODB_USER`:

https://hub.docker.com/r/centos/mongodb-26-centos7/

**Comment by dustymabe** [comment]
@tuxdna thanks for finding this issue. So I think the largest issue that we have right now is that we are not currently building our own Atomic App for mongodb (I didn't realize this before). 

@cdrage can you set up projectatomic/mongodb-centos7-atomicapp to build in docker hub? 

@tuxdna, once we gets that set up let's iterate on it and get this fixed!!

**Comment by dustymabe** [comment]
@cdrage ping

**Comment by tuxdna** [comment]
Appears to be resolved due to:
- https://github.com/projectatomic/nulecule-library/pull/66
- https://github.com/projectatomic/nulecule-library/pull/67

@cdrage 

I think the issue is already fixed in https://github.com/projectatomic/nulecule-library/commit/47583d8450df44f3611e19546bea8262e24ca846. However, I still can't find mongodb atomic app on docker hub here: https://hub.docker.com/u/projectatomic/

**Comment by cdrage** [comment]
@tuxdna yup. this is fixed.

creating the docker hub image now. should be built / created in the next hour!
